### ISSUE TITLE
Image not loading correctly on FF 35 and Safari

### ISSUE THREAD

**Issue by morenoh149** [hzdg/react-imageloader#10]
Hello. Great plugin here.
I'm using it to build http://r3dmqa.herokuapp.com/ but we're having issues getting the animation right
on FF 35 and Safari.
Does react-imageloader support Safari?

**Comment by lettertwo** [comment]
Hey @morenoh149, can you provide a smaller use case or more specifics on the problem you're having? I looked at your link in chrome, firefox and safari, and as far as i can tell, they look and behave the same. What am i missing?

**Comment by morenoh149** [comment]
we fixed it since the question was raised. Thanks.
