### ISSUE TITLE
Set className of <img>?

### ISSUE THREAD

**Issue by idolize** [hzdg/react-imageloader#18]
There is no way to set `className` of the rendered `<img>` tag. This is important to me, and used to work in earlier versions of this library...

The behavior is due to the fact that `className` is in [the property "blacklist"](https://github.com/hzdg/react-imageloader/blob/master/src/index.js#L94).

Perhaps an "`imgClassName`" prop could be added to address this?

**Comment by lettertwo** [comment]
Hmm yeah, maybe a prop is the right solution. Do you mind giving a bit more info on your use case for giving the img a class?

**Comment by idolize** [comment]
Sure, I just want to give my transparent .png image a different color background than white.

I know there are other workarounds, like adding a "`.my-class `**`img`**" to my CSS class definition, or creating an additional wrapper component with my custom background, but styling the image directly is definitely the preferable solution.

Thanks for all the great work!

**Comment by matthewwithanm** [comment]
I wonder if the solution shouldn't be more generic. I mean, what makes "className" so special? Will there be other properties we want to support? Can we come up with something a little more flexible?

**Comment by lettertwo** [comment]
I've been thinking we could make a `imgProps` prop for this.

**Comment by lettertwo** [comment]
To expound: Instead of passing the 'extra' props given to `ImageLoader` down to the `<img>`, pass the value of `imgProps`.

**Comment by pepjo** [comment]
This would be great! This would also work for accessibility tags like "alt".

**Comment by idolize** [comment]
:+1:

**Comment by lettertwo** [comment]
Added the `imgProps`...prop. On npm now as v2.1.0.
