### ISSUE TITLE
Will this project be updated?

### ISSUE THREAD

**Issue by merlinpatt** [hzdg/react-imageloader#44]
@lettertwo, or @johnetrent as another member of this project's organization, are there any plans to update this project?

**Comment by davidfurlong** [comment]
Given the status of this repo (no update in 2 years) I have forked and made some design changes & fixed deprecations which I think are a big improvement https://github.com/DeedMob/react-load-image

**Comment by lettertwo** [comment]
[version 3.0.0](https://www.npmjs.com/package/react-imageloader) is on npm.
